#!/usr/bin/env python3
import json
import uuid
from collections import Counter
from pathlib import Path

NAMESPACE = uuid.UUID("c78c1676-9d72-4b05-90f0-c40d65a44e5c")
LEVEL_DIFFICULTY = {"A1": 1, "A2": 2, "B1": 3, "B2": 4, "C1": 5, "C2": 6}

# Her kayıt: hedef dilde cevap, Türkçe anlam, kategori.
PACKS = {
    "english": {
        "language": "English", "locale": "en_US",
        "levels": {
            "A1": [("ANGRY","Sinirli","Duygular"),("BOOK","Kitap","Eğitim"),("CAT","Kedi","Hayvanlar"),("DOOR","Kapı","Ev"),("EAT","Yemek yemek","Fiiller"),("FAMILY","Aile","İnsanlar"),("GREEN","Yeşil","Renkler"),("HOUSE","Ev","Ev"),("ISLAND","Ada","Doğa"),("JUMP","Zıplamak","Fiiller"),("KITCHEN","Mutfak","Ev"),("LOVE","Sevmek","Duygular"),("MORNING","Sabah","Zaman"),("NIGHT","Gece","Zaman"),("ORANGE","Turuncu","Renkler"),("PENCIL","Kurşun kalem","Eğitim"),("RAIN","Yağmur","Hava"),("SCHOOL","Okul","Eğitim"),("TABLE","Masa","Ev"),("WATER","Su","Yiyecek ve İçecek")],
            "A2": [("AIRPORT","Havalimanı","Seyahat"),("BORROW","Ödünç almak","Fiiller"),("CROWDED","Kalabalık","Sıfatlar"),("DANGEROUS","Tehlikeli","Sıfatlar"),("EXERCISE","Egzersiz","Sağlık"),("FOREST","Orman","Doğa"),("GUEST","Misafir","İnsanlar"),("HEALTHY","Sağlıklı","Sağlık"),("INVITE","Davet etmek","Fiiller"),("JOURNEY","Yolculuk","Seyahat"),("KNIFE","Bıçak","Mutfak"),("LUCKY","Şanslı","Sıfatlar"),("MESSAGE","Mesaj","İletişim"),("NEIGHBOR","Komşu","İnsanlar"),("OFFICE","Ofis","İş"),("PROMISE","Söz vermek","Fiiller"),("REPAIR","Tamir etmek","Fiiller"),("SURPRISED","Şaşırmış","Duygular"),("TICKET","Bilet","Seyahat"),("WORRIED","Endişeli","Duygular")],
            "B1": [("ACHIEVE","Başarmak","Fiiller"),("BEHAVIOR","Davranış","İnsanlar"),("CONFIDENT","Kendine güvenen","Sıfatlar"),("DECREASE","Azalmak","Değişim"),("ENVIRONMENT","Çevre","Doğa"),("FAILURE","Başarısızlık","Soyut Kavramlar"),("GENERous","Cömert","Sıfatlar"),("HABIT","Alışkanlık","Günlük Yaşam"),("IMPROVE","Geliştirmek","Fiiller"),("JUSTICE","Adalet","Toplum"),("KNOWLEDGE","Bilgi","Eğitim"),("LEISURE","Boş zaman","Günlük Yaşam"),("MAINTAIN","Sürdürmek","Fiiller"),("NOTICE","Fark etmek","Fiiller"),("OPPORTUNITY","Fırsat","Soyut Kavramlar"),("POLLUTION","Kirlilik","Doğa"),("REQUIRE","Gerektirmek","Fiiller"),("SOLUTION","Çözüm","Soyut Kavramlar"),("TRADITION","Gelenek","Kültür"),("VOLUNTEER","Gönüllü","Toplum")],
            "B2": [("ASSUMPTION","Varsayım","Düşünce"),("BOUNDARY","Sınır","Soyut Kavramlar"),("CONTROVERSIAL","Tartışmalı","Sıfatlar"),("DELIBERATE","Kasıtlı","Sıfatlar"),("EMPHASIZE","Vurgulamak","İletişim"),("FEASIBLE","Uygulanabilir","Sıfatlar"),("GRADUAL","Kademeli","Sıfatlar"),("HESITATE","Tereddüt etmek","Fiiller"),("INEVITABLE","Kaçınılmaz","Sıfatlar"),("JUSTIFY","Gerekçelendirmek","Fiiller"),("LEGISLATION","Mevzuat","Toplum"),("MISLEADING","Yanıltıcı","Sıfatlar"),("NEGOTIATE","Müzakere etmek","İletişim"),("OBSTACLE","Engel","Soyut Kavramlar"),("PERSPECTIVE","Bakış açısı","Düşünce"),("RELUCTANT","İsteksiz","Sıfatlar"),("SUSTAINABLE","Sürdürülebilir","Doğa"),("THOROUGH","Kapsamlı","Sıfatlar"),("UNDERestimate","Küçümsemek","Fiiller"),("VULNERABLE","Savunmasız","Sıfatlar")],
            "C1": [("AMBIGUOUS","Muğlak","Sıfatlar"),("COHERENT","Tutarlı","Sıfatlar"),("DETERIORATE","Kötüleşmek","Değişim"),("ELABORATE","Ayrıntılı","Sıfatlar"),("FLAWED","Kusurlu","Sıfatlar"),("IMPLICIT","Örtük","İletişim"),("INTRINSIC","İçsel","Soyut Kavramlar"),("METICULOUS","Titiz","Sıfatlar"),("NOTWITHSTANDING","Rağmen","Bağlaçlar"),("PLAUSIBLE","Akla yatkın","Sıfatlar"),("PREVALENT","Yaygın","Sıfatlar"),("REINFORCE","Pekiştirmek","Fiiller"),("SCRUTINY","Titiz inceleme","Düşünce"),("SUBSTANTIAL","Kayda değer","Sıfatlar"),("TENTATIVE","Geçici ve kesin olmayan","Sıfatlar"),("UNPRECEDENTED","Eşi görülmemiş","Sıfatlar"),("VIABLE","Yaşayabilir","Sıfatlar"),("WITHSTAND","Dayanmak","Fiiller"),("YIELD","Sonuç vermek","Fiiller"),("ZEALOUS","Gayretli","Sıfatlar")],
            "C2": [("ABERRATION","Sapma","Soyut Kavramlar"),("BELLIGERENT","Kavgacı","Sıfatlar"),("CONUNDRUM","Çetin bilmece","Düşünce"),("DISSEMINATE","Yaymak","İletişim"),("EQUIVOCAL","İki anlamlı","Sıfatlar"),("FASTIDIOUS","Aşırı titiz","Sıfatlar"),("GARRULOUS","Geveze","Sıfatlar"),("HAPHAZARD","Gelişigüzel","Sıfatlar"),("INTRANSIGENT","Uzlaşmaz","Sıfatlar"),("JUXTAPOSE","Yan yana koymak","Fiiller"),("LACONIC","Az ve öz","Sıfatlar"),("MAGNANIMOUS","Yüce gönüllü","Sıfatlar"),("NEFARIOUS","Alçakça","Sıfatlar"),("OBFUSCATE","Anlaşılmaz hâle getirmek","İletişim"),("PERFUNCTORY","Üstünkörü","Sıfatlar"),("RECALCITRANT","İtaatsiz ve dirençli","Sıfatlar"),("SERENDIPITY","Mutlu tesadüf","Soyut Kavramlar"),("UBIQUITOUS","Her yerde bulunan","Sıfatlar"),("VACILLATE","Kararsız kalmak","Fiiller"),("WISTFUL","Özlemli","Duygular")]
        }
    },
    "italian": {
        "language": "Italian", "locale": "it_IT",
        "levels": {
            "A1": [("ARRABBIATO","Sinirli","Duygular"),("BARCA","Tekne","Seyahat"),("CASA","Ev","Ev"),("DORMIRE","Uyumak","Fiiller"),("ESTATE","Yaz mevsimi","Zaman"),("FAMIGLIA","Aile","İnsanlar"),("GATTO","Kedi","Hayvanlar"),("ISOLA","Ada","Doğa"),("LATTE","Süt","Yiyecek ve İçecek"),("MADRE","Anne","İnsanlar"),("NOTTE","Gece","Zaman"),("OCCHIO","Göz","Vücut"),("PANE","Ekmek","Yiyecek ve İçecek"),("QUADERNO","Defter","Eğitim"),("ROSSO","Kırmızı","Renkler"),("SCUOLA","Okul","Eğitim"),("TAVOLO","Masa","Ev"),("UOMO","Adam","İnsanlar"),("VERDE","Yeşil","Renkler"),("ZAINO","Sırt çantası","Eşyalar")],
            "A2": [("AEROPORTO","Havalimanı","Seyahat"),("BAGNATO","Islak","Sıfatlar"),("CAMMINARE","Yürümek","Fiiller"),("DIMENTICARE","Unutmak","Fiiller"),("ESAME","Sınav","Eğitim"),("FAMOSO","Ünlü","Sıfatlar"),("GENTILE","Nazik","Sıfatlar"),("INVITARE","Davet etmek","Fiiller"),("LAVORO","İş","İş"),("MESSAGGIO","Mesaj","İletişim"),("NEGOZIO","Mağaza","Alışveriş"),("OSPITE","Misafir","İnsanlar"),("PERICOLOSO","Tehlikeli","Sıfatlar"),("REGALO","Hediye","Eşyalar"),("SALUTE","Sağlık","Sağlık"),("TEMPORALE","Fırtına","Hava"),("UTILE","Yararlı","Sıfatlar"),("VACANZA","Tatil","Seyahat"),("VICINO","Komşu","İnsanlar"),("ZUCCHERO","Şeker","Yiyecek ve İçecek")],
            "B1": [("ABITUDINE","Alışkanlık","Günlük Yaşam"),("COMPORTAMENTO","Davranış","İnsanlar"),("DIMINUIRE","Azalmak","Değişim"),("ESPERIENZA","Deneyim","Soyut Kavramlar"),("FALLIMENTO","Başarısızlık","Soyut Kavramlar"),("GENEROSO","Cömert","Sıfatlar"),("GIUSTIZIA","Adalet","Toplum"),("MIGLIORARE","Geliştirmek","Fiiller"),("OCCASIONE","Fırsat","Soyut Kavramlar"),("PERMETTERE","İzin vermek","Fiiller"),("RAGGIUNGERE","Ulaşmak","Fiiller"),("RESPONSABILE","Sorumlu","Sıfatlar"),("SCELTA","Seçim","Soyut Kavramlar"),("SOLUZIONE","Çözüm","Soyut Kavramlar"),("SOSTENERE","Desteklemek","Fiiller"),("TRADIZIONE","Gelenek","Kültür"),("VOLONTARIO","Gönüllü","Toplum"),("AMBIENTE","Çevre","Doğa"),("CONOSCENZA","Bilgi","Eğitim"),("INQUINAMENTO","Kirlilik","Doğa")],
            "B2": [("AFFIDABILE","Güvenilir","Sıfatlar"),("CONFINE","Sınır","Soyut Kavramlar"),("CONTROVERSO","Tartışmalı","Sıfatlar"),("EVIDENZIARE","Vurgulamak","İletişim"),("FATTIBILE","Uygulanabilir","Sıfatlar"),("GRADUALE","Kademeli","Sıfatlar"),("INEVITABILE","Kaçınılmaz","Sıfatlar"),("LEGISLAZIONE","Mevzuat","Toplum"),("NEGOZIARE","Müzakere etmek","İletişim"),("OSTACOLO","Engel","Soyut Kavramlar"),("PROSPETTIVA","Bakış açısı","Düşünce"),("RILUTTANTE","İsteksiz","Sıfatlar"),("SOSTENIBILE","Sürdürülebilir","Doğa"),("SOTTOVALUTARE","Küçümsemek","Fiiller"),("VULNERABILE","Savunmasız","Sıfatlar"),("ESITARE","Tereddüt etmek","Fiiller"),("FUORVIANTE","Yanıltıcı","Sıfatlar"),("GIUSTIFICARE","Gerekçelendirmek","Fiiller"),("PRESUPPOSTO","Varsayım","Düşünce"),("SCRUPOLOSO","Özenli","Sıfatlar")],
            "C1": [("AMBIGUO","Muğlak","Sıfatlar"),("COERENTE","Tutarlı","Sıfatlar"),("DETERIORARSI","Kötüleşmek","Değişim"),("ELABORATO","Ayrıntılı","Sıfatlar"),("IMPLICITO","Örtük","İletişim"),("INTRINSECO","İçsel","Soyut Kavramlar"),("METICOLOSO","Titiz","Sıfatlar"),("PLAUSIBILE","Akla yatkın","Sıfatlar"),("PREVALENTE","Yaygın","Sıfatlar"),("RAFFORZARE","Pekiştirmek","Fiiller"),("SOSTANZIALE","Kayda değer","Sıfatlar"),("PROVVISORIO","Geçici","Sıfatlar"),("SENZA PRECEDENTI","Eşi görülmemiş","Sıfatlar"),("RESISTERE","Dayanmak","Fiiller"),("RENDIMENTO","Verim","İş"),("ZELOSO","Gayretli","Sıfatlar"),("APPROFONDIMENTO","Derinlemesine inceleme","Düşünce"),("COMPROMESSO","Uzlaşma","Toplum"),("PERSISTENTE","Kalıcı ve ısrarcı","Sıfatlar"),("TRASCURABILE","İhmal edilebilir","Sıfatlar")],
            "C2": [("ABERRAZIONE","Sapma","Soyut Kavramlar"),("BELLICOSO","Kavgacı","Sıfatlar"),("DILEMMA","Çetin ikilem","Düşünce"),("DISSEMINARE","Yaymak","İletişim"),("EQUIVOCO","İki anlamlı","Sıfatlar"),("FASTIDIOSO","Aşırı seçici","Sıfatlar"),("LOQUACE","Geveze","Sıfatlar"),("INTRANSIGENTE","Uzlaşmaz","Sıfatlar"),("LACONICO","Az ve öz","Sıfatlar"),("MAGNANIMO","Yüce gönüllü","Sıfatlar"),("NEFANDO","Alçakça","Sıfatlar"),("OFFUSCARE","Anlaşılmaz hâle getirmek","İletişim"),("PERFUNCTORIO","Üstünkörü","Sıfatlar"),("RECAlCITRANTE","İtaatsiz ve dirençli","Sıfatlar"),("SERENDIPITÀ","Mutlu tesadüf","Soyut Kavramlar"),("UBIQUO","Her yerde bulunan","Sıfatlar"),("VACILLARE","Kararsız kalmak","Fiiller"),("NOSTALGICO","Özlemli","Duygular"),("GIUSTAPPORRE","Yan yana koymak","Fiiller"),("INEFFABILE","Sözcüklerle anlatılamaz","Sıfatlar")]
        }
    },
    "german": {
        "language": "German", "locale": "de_DE",
        "levels": {
            "A1": [("ÄRGERLICH","Sinirli","Duygular"),("BUCH","Kitap","Eğitim"),("DORF","Köy","Yerler"),("ESSEN","Yemek yemek","Fiiller"),("FAMILIE","Aile","İnsanlar"),("GRÜN","Yeşil","Renkler"),("HAUS","Ev","Ev"),("INSEL","Ada","Doğa"),("JUNG","Genç","Sıfatlar"),("KATZE","Kedi","Hayvanlar"),("LIEBE","Sevgi","Duygular"),("MORGEN","Sabah","Zaman"),("NACHT","Gece","Zaman"),("ORANGE","Turuncu","Renkler"),("PFERD","At","Hayvanlar"),("REGEN","Yağmur","Hava"),("SCHULE","Okul","Eğitim"),("TISCH","Masa","Ev"),("WASSER","Su","Yiyecek ve İçecek"),("ZIMMER","Oda","Ev")],
            "A2": [("FLUGHAFEN","Havalimanı","Seyahat"),("AUSLEIHEN","Ödünç almak","Fiiller"),("GEFÄHRLICH","Tehlikeli","Sıfatlar"),("GESUND","Sağlıklı","Sağlık"),("GAST","Misafir","İnsanlar"),("EINLADEN","Davet etmek","Fiiller"),("NACHRICHT","Mesaj","İletişim"),("NACHBAR","Komşu","İnsanlar"),("BÜRO","Ofis","İş"),("VERSPRECHEN","Söz vermek","Fiiller"),("REPARIEREN","Tamir etmek","Fiiller"),("ÜBERRASCHT","Şaşırmış","Duygular"),("FAHRKARTE","Bilet","Seyahat"),("BESORGT","Endişeli","Duygular"),("ÜBUNG","Egzersiz","Sağlık"),("WALD","Orman","Doğa"),("REISE","Yolculuk","Seyahat"),("MESSER","Bıçak","Mutfak"),("GLÜCKLICH","Şanslı","Sıfatlar"),("VOLL","Kalabalık ve dolu","Sıfatlar")],
            "B1": [("ERREICHEN","Başarmak","Fiiller"),("VERHALTEN","Davranış","İnsanlar"),("SELBSTBEWUSST","Kendine güvenen","Sıfatlar"),("ABNEHMEN","Azalmak","Değişim"),("UMWELT","Çevre","Doğa"),("MISSERFOLG","Başarısızlık","Soyut Kavramlar"),("GROSSZÜGIG","Cömert","Sıfatlar"),("GEWOHNHEIT","Alışkanlık","Günlük Yaşam"),("VERBESSERN","Geliştirmek","Fiiller"),("GERECHTIGKEIT","Adalet","Toplum"),("WISSEN","Bilgi","Eğitim"),("FREIZEIT","Boş zaman","Günlük Yaşam"),("ERHALTEN","Sürdürmek","Fiiller"),("BEMERKEN","Fark etmek","Fiiller"),("GELEGENHEIT","Fırsat","Soyut Kavramlar"),("VERSCHMUTZUNG","Kirlilik","Doğa"),("ERFORDERN","Gerektirmek","Fiiller"),("LÖSUNG","Çözüm","Soyut Kavramlar"),("TRADITION","Gelenek","Kültür"),("FREIWILLIGER","Gönüllü","Toplum")],
            "B2": [("ANNAHME","Varsayım","Düşünce"),("GRENZE","Sınır","Soyut Kavramlar"),("UMSTRITTEN","Tartışmalı","Sıfatlar"),("ABSICHTLICH","Kasıtlı","Sıfatlar"),("BETONEN","Vurgulamak","İletişim"),("MACHBAR","Uygulanabilir","Sıfatlar"),("ALLMÄHLICH","Kademeli","Sıfatlar"),("ZÖGERN","Tereddüt etmek","Fiiller"),("UNVERMEIDLICH","Kaçınılmaz","Sıfatlar"),("RECHTFERTIGEN","Gerekçelendirmek","Fiiller"),("GESETZGEBUNG","Mevzuat","Toplum"),("IRREFÜHREND","Yanıltıcı","Sıfatlar"),("VERHANDELN","Müzakere etmek","İletişim"),("HINDERNIS","Engel","Soyut Kavramlar"),("PERSPEKTIVE","Bakış açısı","Düşünce"),("WIDERWILLIG","İsteksiz","Sıfatlar"),("NACHHALTIG","Sürdürülebilir","Doğa"),("GRÜNDLICH","Kapsamlı","Sıfatlar"),("UNTERSCHÄTZEN","Küçümsemek","Fiiller"),("VERLETZLICH","Savunmasız","Sıfatlar")],
            "C1": [("MEHRDEUTIG","Muğlak","Sıfatlar"),("KOHÄRENT","Tutarlı","Sıfatlar"),("VERSCHLECHTERN","Kötüleşmek","Değişim"),("AUSGEARBEITET","Ayrıntılı","Sıfatlar"),("FEHLERHAFT","Kusurlu","Sıfatlar"),("IMPLIZIT","Örtük","İletişim"),("INTRINSISCH","İçsel","Soyut Kavramlar"),("AKRIBISCH","Titiz","Sıfatlar"),("UNGEACHTET","Rağmen","Bağlaçlar"),("PLAUSIBEL","Akla yatkın","Sıfatlar"),("VERBREITET","Yaygın","Sıfatlar"),("VERSTÄRKEN","Pekiştirmek","Fiiller"),("PRÜFUNG","Titiz inceleme","Düşünce"),("ERHEBLICH","Kayda değer","Sıfatlar"),("VORLÄUFIG","Geçici ve kesin olmayan","Sıfatlar"),("BEISPIELLOS","Eşi görülmemiş","Sıfatlar"),("TRAGFÄHIG","Yaşayabilir","Sıfatlar"),("WIDERSTEHEN","Dayanmak","Fiiller"),("ERGEBEN","Sonuç vermek","Fiiller"),("EIFRIG","Gayretli","Sıfatlar")],
            "C2": [("ABWEICHUNG","Sapma","Soyut Kavramlar"),("STREITLUSTIG","Kavgacı","Sıfatlar"),("ZWICKMÜHLE","Çetin ikilem","Düşünce"),("VERBREITEN","Yaymak","İletişim"),("DOPPELDEUTIG","İki anlamlı","Sıfatlar"),("PEDANTISCH","Aşırı titiz","Sıfatlar"),("GESCHWÄTZIG","Geveze","Sıfatlar"),("PLANLOS","Gelişigüzel","Sıfatlar"),("UNNACHGIEBIG","Uzlaşmaz","Sıfatlar"),("GEGENÜBERSTELLEN","Yan yana koymak","Fiiller"),("WORTKARG","Az ve öz","Sıfatlar"),("GROSSMÜTIG","Yüce gönüllü","Sıfatlar"),("RÜCHLOS","Alçakça","Sıfatlar"),("VERSCHLEIERN","Anlaşılmaz hâle getirmek","İletişim"),("OBERFLÄCHLICH","Üstünkörü","Sıfatlar"),("WIDERSPENSTIG","İtaatsiz ve dirençli","Sıfatlar"),("GLÜCKSFUND","Mutlu tesadüf","Soyut Kavramlar"),("ALLGEGENWÄRTIG","Her yerde bulunan","Sıfatlar"),("SCHWANKEN","Kararsız kalmak","Fiiller"),("WEHMÜTIG","Özlemli","Duygular")]
        }
    }
}

# İlk 120 kayıttan farklı cevaplardan oluşan ikinci 120 kayıt.
EXTRA_PACKS = {
"english": {
"A1": [("APPLE","Elma","Yiyecek ve İçecek"),("BABY","Bebek","İnsanlar"),("CHAIR","Sandalye","Ev"),("DOG","Köpek","Hayvanlar"),("EAR","Kulak","Vücut"),("FISH","Balık","Hayvanlar"),("GARDEN","Bahçe","Ev"),("HAPPY","Mutlu","Duygular"),("ICE","Buz","Doğa"),("JOB","Meslek","İş"),("KEY","Anahtar","Eşyalar"),("LEMON","Limon","Yiyecek ve İçecek"),("MONEY","Para","Alışveriş"),("NAME","İsim","İnsanlar"),("OPEN","Açmak","Fiiller"),("PHONE","Telefon","Teknoloji"),("QUESTION","Soru","Eğitim"),("RUN","Koşmak","Fiiller"),("SUN","Güneş","Doğa"),("TREE","Ağaç","Doğa")],
"A2": [("APPOINTMENT","Randevu","Günlük Yaşam"),("BRIDGE","Köprü","Yerler"),("CHEAP","Ucuz","Alışveriş"),("DECIDE","Karar vermek","Fiiller"),("EMPTY","Boş","Sıfatlar"),("FUTURE","Gelecek","Zaman"),("GROUND","Zemin","Doğa"),("HOSPITAL","Hastane","Sağlık"),("IMPORTANT","Önemli","Sıfatlar"),("JACKET","Ceket","Giyim"),("KNOCK","Kapıyı çalmak","Fiiller"),("LANGUAGE","Dil","Eğitim"),("MUSEUM","Müze","Kültür"),("NOISY","Gürültülü","Sıfatlar"),("OFFER","Teklif etmek","Fiiller"),("POLITE","Kibar","Sıfatlar"),("QUIET","Sessiz","Sıfatlar"),("RETURN","Geri dönmek","Fiiller"),("SPECIAL","Özel","Sıfatlar"),("THIRSTY","Susamış","Sağlık")],
"B1": [("ADVICE","Tavsiye","İletişim"),("BENEFIT","Fayda","Soyut Kavramlar"),("CHALLENGE","Zorluk","Soyut Kavramlar"),("DEMAND","Talep","İş"),("EFFORT","Çaba","Soyut Kavramlar"),("FREEDOM","Özgürlük","Toplum"),("GOAL","Hedef","Soyut Kavramlar"),("HARM","Zarar","Soyut Kavramlar"),("INCREASE","Artırmak","Değişim"),("JUDGE","Yargılamak","Fiiller"),("LEADERSHIP","Liderlik","İş"),("MEASURE","Ölçmek","Fiiller"),("NATURAL","Doğal","Sıfatlar"),("OUTCOME","Sonuç","Soyut Kavramlar"),("PATIENT","Sabırlı","Sıfatlar"),("QUALITY","Kalite","İş"),("RELATIONSHIP","İlişki","İnsanlar"),("SKILL","Beceri","Eğitim"),("TRUST","Güven","Duygular"),("VALUE","Değer","Soyut Kavramlar")],
"B2": [("ACCOUNTABLE","Hesap verebilir","Sıfatlar"),("BIAS","Önyargı","Düşünce"),("COMPELLING","İkna edici","Sıfatlar"),("DIVERSE","Çeşitli","Sıfatlar"),("ETHICAL","Etik","Toplum"),("FLEXIBLE","Esnek","Sıfatlar"),("GOVERNANCE","Yönetişim","Toplum"),("HYPOTHESIS","Hipotez","Bilim"),("INCENTIVE","Teşvik","İş"),("JURISDICTION","Yargı yetkisi","Toplum"),("LEGITIMATE","Meşru","Sıfatlar"),("MANIPULATE","Yönlendirmek","Fiiller"),("NEUTRAL","Tarafsız","Sıfatlar"),("OBJECTIVE","Nesnel","Sıfatlar"),("PRIORITY","Öncelik","İş"),("QUESTIONABLE","Şüpheli","Sıfatlar"),("RESILIENT","Dayanıklı","Sıfatlar"),("SIGNIFICANT","Önemli","Sıfatlar"),("TRANSPARENT","Şeffaf","Sıfatlar"),("UNCERTAIN","Belirsiz","Sıfatlar")],
"C1": [("ARBITRARY","Keyfî","Sıfatlar"),("CONCISE","Özlü","İletişim"),("DISCREPANCY","Tutarsızlık","Düşünce"),("EMPIRICAL","Deneysel verilere dayalı","Bilim"),("FORMIDABLE","Çetin ve etkileyici","Sıfatlar"),("HOLISTIC","Bütüncül","Düşünce"),("INDISPENSABLE","Vazgeçilmez","Sıfatlar"),("JUDICIOUS","Sağduyulu","Sıfatlar"),("LEGITIMACY","Meşruiyet","Toplum"),("MITIGATE","Hafifletmek","Fiiller"),("NUANCED","İnce ayrımları olan","Sıfatlar"),("OMINOUS","Uğursuz","Sıfatlar"),("PARADIGM","Düşünce modeli","Düşünce"),("QUANTIFY","Nicelleştirmek","Bilim"),("ROBUST","Sağlam","Sıfatlar"),("SKEPTICAL","Şüpheci","Sıfatlar"),("TRANSIENT","Geçici","Sıfatlar"),("UNDERSCORE","Altını çizmek","İletişim"),("VALIDATE","Doğrulamak","Bilim"),("WARRANTED","Gerekçeli","Sıfatlar")],
"C2": [("ANACHRONISTIC","Çağdışı","Sıfatlar"),("BYZANTINE","Aşırı karmaşık","Sıfatlar"),("CIRCUMLOCUTION","Dolaylı anlatım","İletişim"),("DELETERIOUS","Zararlı","Sıfatlar"),("EXACERBATE","Daha kötü hâle getirmek","Fiiller"),("FALLACIOUS","Safsataya dayalı","Sıfatlar"),("HERMENEUTICS","Yorum bilimi","Bilim"),("ICONOCLASTIC","Yerleşik inançlara karşı çıkan","Sıfatlar"),("JEJUNE","Yüzeysel ve sıkıcı","Sıfatlar"),("KNAVISH","Hilekâr","Sıfatlar"),("LUGUBRIOUS","Kasvetli","Sıfatlar"),("MENDACIOUS","Yalancı","Sıfatlar"),("NONCHALANT","Aldırışsız","Sıfatlar"),("OSTENSIBLE","Görünürdeki","Sıfatlar"),("QUOTIDIAN","Gündelik","Sıfatlar"),("SAGACIOUS","Bilgece","Sıfatlar"),("TRENCHANT","Keskin ve etkili","Sıfatlar"),("UNTENABLE","Savunulamaz","Sıfatlar"),("VERISIMILITUDE","Gerçeğe benzerlik","Soyut Kavramlar"),("ZEITGEIST","Çağın ruhu","Kültür")]
},
"italian": {
"A1": [("ACQUA","Su","Yiyecek ve İçecek"),("BAMBINO","Çocuk","İnsanlar"),("CANE","Köpek","Hayvanlar"),("DENTe","Diş","Vücut"),("ERBA","Çimen","Doğa"),("FIORE","Çiçek","Doğa"),("GIORNO","Gün","Zaman"),("HOTEL","Otel","Seyahat"),("INVERNO","Kış","Zaman"),("LUNA","Ay","Doğa"),("MANO","El","Vücut"),("NOME","İsim","İnsanlar"),("PORTA","Kapı","Ev"),("QUATTRO","Dört","Sayılar"),("RAGAZZA","Kız","İnsanlar"),("SOLE","Güneş","Doğa"),("TRENO","Tren","Seyahat"),("UOVO","Yumurta","Yiyecek ve İçecek"),("VINO","Şarap","Yiyecek ve İçecek"),("ZERO","Sıfır","Sayılar")],
"A2": [("APPUNTAMENTO","Randevu","Günlük Yaşam"),("BASSO","Alçak ve kısa","Sıfatlar"),("COSTOSO","Pahalı","Alışveriş"),("DECIDERE","Karar vermek","Fiiller"),("FUTURO","Gelecek","Zaman"),("GUARIRE","İyileşmek","Sağlık"),("IMPROVVISO","Ani","Sıfatlar"),("LINGUA","Dil","Eğitim"),("MUSEO","Müze","Kültür"),("RUMOROSO","Gürültülü","Sıfatlar"),("OFFRIRE","Teklif etmek","Fiiller"),("PAZIENTE","Sabırlı","Sıfatlar"),("RITORNARE","Geri dönmek","Fiiller"),("SPECIALE","Özel","Sıfatlar"),("ASSETATO","Susamış","Sağlık"),("VUOTO","Boş","Sıfatlar"),("PONTE","Köprü","Yerler"),("GIACCA","Ceket","Giyim"),("BUSSARE","Kapıyı çalmak","Fiiller"),("TRANQUILLO","Sessiz ve sakin","Sıfatlar")],
"B1": [("CONSIGLIO","Tavsiye","İletişim"),("BENEFICIO","Fayda","Soyut Kavramlar"),("SFIDA","Zorluk","Soyut Kavramlar"),("RICHIESTA","Talep","İş"),("SFORZO","Çaba","Soyut Kavramlar"),("LIBERTÀ","Özgürlük","Toplum"),("OBIETTIVO","Hedef","Soyut Kavramlar"),("DANNO","Zarar","Soyut Kavramlar"),("AUMENTARE","Artırmak","Değişim"),("GIUDICARE","Yargılamak","Fiiller"),("LEADERSHIP","Liderlik","İş"),("MISURARE","Ölçmek","Fiiller"),("NATURALE","Doğal","Sıfatlar"),("ESITO","Sonuç","Soyut Kavramlar"),("QUALITÀ","Kalite","İş"),("RELAZIONE","İlişki","İnsanlar"),("ABILITÀ","Beceri","Eğitim"),("FIDUCIA","Güven","Duygular"),("VALORE","Değer","Soyut Kavramlar"),("PROGRESSO","İlerleme","Değişim")],
"B2": [("RESPONSABILE","Hesap verebilir","Sıfatlar"),("PREGIUDIZIO","Önyargı","Düşünce"),("CONVINCENTE","İkna edici","Sıfatlar"),("DIVERSO","Çeşitli","Sıfatlar"),("ETICO","Etik","Toplum"),("FLESSIBILE","Esnek","Sıfatlar"),("GOVERNANCE","Yönetişim","Toplum"),("IPOTESI","Hipotez","Bilim"),("INCENTIVO","Teşvik","İş"),("GIURISDIZIONE","Yargı yetkisi","Toplum"),("LEGITTIMO","Meşru","Sıfatlar"),("MANIPOLARE","Yönlendirmek","Fiiller"),("NEUTRALE","Tarafsız","Sıfatlar"),("OGGETTIVO","Nesnel","Sıfatlar"),("PRIORITÀ","Öncelik","İş"),("DISCUTIBILE","Şüpheli","Sıfatlar"),("RESILIENTE","Dayanıklı","Sıfatlar"),("SIGNIFICATIVO","Önemli","Sıfatlar"),("TRASPARENTE","Şeffaf","Sıfatlar"),("INCERTO","Belirsiz","Sıfatlar")],
"C1": [("ARBITRARIO","Keyfî","Sıfatlar"),("CONCISO","Özlü","İletişim"),("DISCREPANZA","Tutarsızlık","Düşünce"),("EMPIRICO","Deneysel verilere dayalı","Bilim"),("FORMIDABILE","Çetin ve etkileyici","Sıfatlar"),("OLISTICO","Bütüncül","Düşünce"),("INDISPENSABILE","Vazgeçilmez","Sıfatlar"),("GIUDIZIOSO","Sağduyulu","Sıfatlar"),("LEGITTIMITÀ","Meşruiyet","Toplum"),("MITIGARE","Hafifletmek","Fiiller"),("SFUMATO","İnce ayrımları olan","Sıfatlar"),("INFAUSTO","Uğursuz","Sıfatlar"),("PARADIGMA","Düşünce modeli","Düşünce"),("QUANTIFICARE","Nicelleştirmek","Bilim"),("ROBUSTO","Sağlam","Sıfatlar"),("SCETTICO","Şüpheci","Sıfatlar"),("TRANSITORIO","Geçici","Sıfatlar"),("SOTTOLINEARE","Altını çizmek","İletişim"),("CONVALIDARE","Doğrulamak","Bilim"),("GIUSTIFICATO","Gerekçeli","Sıfatlar")],
"C2": [("ANACRONISTICO","Çağdışı","Sıfatlar"),("BIZANTINO","Aşırı karmaşık","Sıfatlar"),("PERIFRASI","Dolaylı anlatım","İletişim"),("DELETERIO","Zararlı","Sıfatlar"),("ESACERBARE","Daha kötü hâle getirmek","Fiiller"),("FALLACE","Safsataya dayalı","Sıfatlar"),("ERMENEUTICA","Yorum bilimi","Bilim"),("ICONOCLASTA","Yerleşik inançlara karşı çıkan","Sıfatlar"),("INSULSO","Yüzeysel ve sıkıcı","Sıfatlar"),("FURFANTESCO","Hilekâr","Sıfatlar"),("LUGUBRE","Kasvetli","Sıfatlar"),("MENDACE","Yalancı","Sıfatlar"),("DISINVOLTO","Aldırışsız","Sıfatlar"),("APPARENTE","Görünürdeki","Sıfatlar"),("QUOTIDIANO","Gündelik","Sıfatlar"),("SAGACE","Bilgece","Sıfatlar"),("INCISIVO","Keskin ve etkili","Sıfatlar"),("INSOSTENIBILE","Savunulamaz","Sıfatlar"),("VEROSIMIGLIANZA","Gerçeğe benzerlik","Soyut Kavramlar"),("SPIRITO DEL TEMPO","Çağın ruhu","Kültür")]
},
"german": {
"A1": [("APFEL","Elma","Yiyecek ve İçecek"),("BABY","Bebek","İnsanlar"),("STUHL","Sandalye","Ev"),("HUND","Köpek","Hayvanlar"),("OHR","Kulak","Vücut"),("FISCH","Balık","Hayvanlar"),("GARTEN","Bahçe","Ev"),("FROH","Mutlu","Duygular"),("EIS","Buz","Doğa"),("BERUF","Meslek","İş"),("SCHLÜSSEL","Anahtar","Eşyalar"),("ZITRONE","Limon","Yiyecek ve İçecek"),("GELD","Para","Alışveriş"),("NAME","İsim","İnsanlar"),("ÖFFNEN","Açmak","Fiiller"),("HANDY","Cep telefonu","Teknoloji"),("FRAGE","Soru","Eğitim"),("LAUFEN","Koşmak","Fiiller"),("SONNE","Güneş","Doğa"),("BAUM","Ağaç","Doğa")],
"A2": [("TERMIN","Randevu","Günlük Yaşam"),("BRÜCKE","Köprü","Yerler"),("BILLIG","Ucuz","Alışveriş"),("ENTSCHEIDEN","Karar vermek","Fiiller"),("LEER","Boş","Sıfatlar"),("ZUKUNFT","Gelecek","Zaman"),("BODEN","Zemin","Doğa"),("KRANKENHAUS","Hastane","Sağlık"),("WICHTIG","Önemli","Sıfatlar"),("JACKE","Ceket","Giyim"),("KLOPFEN","Kapıyı çalmak","Fiiller"),("SPRACHE","Dil","Eğitim"),("MUSEUM","Müze","Kültür"),("LAUT","Gürültülü","Sıfatlar"),("ANBIETEN","Teklif etmek","Fiiller"),("HÖFLICH","Kibar","Sıfatlar"),("RUHIG","Sessiz","Sıfatlar"),("ZURÜCKKEHREN","Geri dönmek","Fiiller"),("BESONDERS","Özel","Sıfatlar"),("DURSTIG","Susamış","Sağlık")],
"B1": [("RAT","Tavsiye","İletişim"),("VORTEIL","Fayda","Soyut Kavramlar"),("HERAUSFORDERUNG","Zorluk","Soyut Kavramlar"),("NACHFRAGE","Talep","İş"),("ANSTRENGUNG","Çaba","Soyut Kavramlar"),("FREIHEIT","Özgürlük","Toplum"),("ZIEL","Hedef","Soyut Kavramlar"),("SCHADEN","Zarar","Soyut Kavramlar"),("STEIGERN","Artırmak","Değişim"),("BEURTEILEN","Yargılamak","Fiiller"),("FÜHRUNG","Liderlik","İş"),("MESSEN","Ölçmek","Fiiller"),("NATÜRLICH","Doğal","Sıfatlar"),("ERGEBNIS","Sonuç","Soyut Kavramlar"),("GEDULDIG","Sabırlı","Sıfatlar"),("QUALITÄT","Kalite","İş"),("BEZIEHUNG","İlişki","İnsanlar"),("FÄHIGKEIT","Beceri","Eğitim"),("VERTRAUEN","Güven","Duygular"),("WERT","Değer","Soyut Kavramlar")],
"B2": [("VERANTWORTLICH","Hesap verebilir","Sıfatlar"),("VOREINGENOMMENHEIT","Önyargı","Düşünce"),("ÜBERZEUGEND","İkna edici","Sıfatlar"),("VIELFÄLTIG","Çeşitli","Sıfatlar"),("ETHISCH","Etik","Toplum"),("FLEXIBEL","Esnek","Sıfatlar"),("REGIERUNGSFÜHRUNG","Yönetişim","Toplum"),("HYPOTHESE","Hipotez","Bilim"),("ANREIZ","Teşvik","İş"),("GERICHTSBARKEIT","Yargı yetkisi","Toplum"),("LEGITIM","Meşru","Sıfatlar"),("MANIPULIEREN","Yönlendirmek","Fiiller"),("NEUTRAL","Tarafsız","Sıfatlar"),("OBJEKTIV","Nesnel","Sıfatlar"),("PRIORITÄT","Öncelik","İş"),("FRAGWÜRDIG","Şüpheli","Sıfatlar"),("WIDERSTANDSFÄHIG","Dayanıklı","Sıfatlar"),("BEDEUTSAM","Önemli","Sıfatlar"),("TRANSPARENT","Şeffaf","Sıfatlar"),("UNGEWISS","Belirsiz","Sıfatlar")],
"C1": [("WILLKÜRLICH","Keyfî","Sıfatlar"),("PRÄGNANT","Özlü","İletişim"),("DISKREPANZ","Tutarsızlık","Düşünce"),("EMPIRISCH","Deneysel verilere dayalı","Bilim"),("FURCHTEINFLÖSSEND","Çetin ve etkileyici","Sıfatlar"),("GANZHEITLICH","Bütüncül","Düşünce"),("UNENTBEHRLICH","Vazgeçilmez","Sıfatlar"),("BESONNEN","Sağduyulu","Sıfatlar"),("LEGITIMITÄT","Meşruiyet","Toplum"),("MILDERN","Hafifletmek","Fiiller"),("NUANCIERT","İnce ayrımları olan","Sıfatlar"),("UNHEILVOLL","Uğursuz","Sıfatlar"),("PARADIGMA","Düşünce modeli","Düşünce"),("QUANTIFIZIEREN","Nicelleştirmek","Bilim"),("ROBUST","Sağlam","Sıfatlar"),("SKEPTISCH","Şüpheci","Sıfatlar"),("VORÜBERGEHEND","Geçici","Sıfatlar"),("UNTERSTREICHEN","Altını çizmek","İletişim"),("VALIDIEREN","Doğrulamak","Bilim"),("BERECHTIGT","Gerekçeli","Sıfatlar")],
"C2": [("ANACHRONISTISCH","Çağdışı","Sıfatlar"),("BYZANTINISCH","Aşırı karmaşık","Sıfatlar"),("UMSCHWEIF","Dolaylı anlatım","İletişim"),("SCHÄDLICH","Zararlı","Sıfatlar"),("VERSCHÄRFEN","Daha kötü hâle getirmek","Fiiller"),("TRÜGERISCH","Safsataya dayalı","Sıfatlar"),("HERMENEUTIK","Yorum bilimi","Bilim"),("IKONOKLASTISCH","Yerleşik inançlara karşı çıkan","Sıfatlar"),("GEISTLOS","Yüzeysel ve sıkıcı","Sıfatlar"),("SCHURKISCH","Hilekâr","Sıfatlar"),("DÜSTER","Kasvetli","Sıfatlar"),("VERLOGEN","Yalancı","Sıfatlar"),("LÄSSIG","Aldırışsız","Sıfatlar"),("VORGEBLICH","Görünürdeki","Sıfatlar"),("ALLTÄGLICH","Gündelik","Sıfatlar"),("SCHARFSINNIG","Bilgece","Sıfatlar"),("SCHARFZÜNGIG","Keskin ve etkili","Sıfatlar"),("UNHALTBAR","Savunulamaz","Sıfatlar"),("WAHRSCHEINLICHKEIT","Gerçeğe benzerlik","Soyut Kavramlar"),("ZEITGEIST","Çağın ruhu","Kültür")]
}}

ALPHABETS = {
    "english": list("ABCDEFGHIJKLMNOPQRSTUVWXYZ"),
    "italian": list("ABCDEFGHILMNOPQRSTUVZ"),
    "german": list("ABCDEFGHIJKLMNOPQRSTUVWXYZÄÖÜ"),
}

# Her dil/seviye çemberindeki her harfin oynanabilir olmasını garanti eden kayıtlar.
# Bunlar yalnızca ilgili harf temel 40 soruda yoksa, fazla temsil edilen bir harfin
# kaydıyla değiştirilir; böylece seviye başına soru sayısı 40 olarak kalır.
COVERAGE_PACKS = {
    "english": {
        "A1": [("UMBRELLA", "Şemsiye", "Eşyalar"), ("VAN", "Minibüs", "Ulaşım"), ("XYLOPHONE", "Ksilofon", "Müzik"), ("YELLOW", "Sarı", "Renkler"), ("ZOO", "Hayvanat bahçesi", "Yerler")],
        "A2": [("UNIFORM", "Üniforma", "Giyim"), ("VILLAGE", "Köy", "Yerler"), ("X-RAY", "Röntgen", "Sağlık"), ("YOGURT", "Yoğurt", "Yiyecek ve İçecek"), ("ZIPPER", "Fermuar", "Giyim")],
        "B1": [("UPDATE", "Güncellemek", "Teknoloji"), ("WASTE", "Atık", "Çevre"), ("XENOPHOBIA", "Yabancı düşmanlığı", "Toplum"), ("YOUTH", "Gençlik", "İnsanlar"), ("ZONE", "Bölge", "Yerler")],
        "B2": [("KINETIC", "Hareketle ilgili", "Bilim"), ("WELFARE", "Refah", "Toplum"), ("XENOPHOBIC", "Yabancı düşmanı", "Sıfatlar"), ("YEARNING", "Özlem", "Duygular"), ("ZEAL", "Gayret", "Duygular")],
        "C1": [("BREVITY", "Özlülük", "İletişim"), ("GRANULAR", "İnce ayrıntılı", "Sıfatlar"), ("KUDOS", "Takdir", "İletişim"), ("XENIAL", "Konuksever", "Sıfatlar")],
        "C2": [("XENODOCHIAL", "Yabancılara karşı konuksever", "Sıfatlar"), ("YARE", "Çevik ve hazır", "Sıfatlar")],
    },
    "italian": {
        "A1": [],
        "A2": [("HO", "Sahibim; avere fiilinin ben çekimi", "Fiiller"), ("QUINDI", "Bu yüzden", "Bağlaçlar")],
        "B1": [("HOBBY", "Hobi", "Günlük Yaşam"), ("URGENZA", "Aciliyet", "Soyut Kavramlar"), ("ZONA", "Bölge", "Yerler")],
        "B2": [("BIASIMO", "Kınama", "Duygular"), ("HABITAT", "Yaşam alanı", "Doğa"), ("QUESITO", "Soru ve mesele", "İletişim"), ("UTOPIA", "Ütopya", "Düşünce"), ("ZELO", "Gayret", "Duygular")],
        "C1": [("BENEVOLO", "İyiliksever", "Sıfatlar"), ("HUMUS", "Toprağın organik katmanı", "Doğa"), ("NESSO", "Bağlantı", "Soyut Kavramlar"), ("UNIVOCO", "Tek anlamlı", "Sıfatlar"), ("VAGLIARE", "Dikkatle değerlendirmek", "Fiiller")],
        "C2": [("CAVILLO", "Önemsiz ve kurnazca itiraz", "İletişim"), ("HINTERLAND", "İç bölge", "Yerler"), ("TAUTOLOGIA", "Aynı düşünceyi yineleme", "İletişim"), ("ZELOTA", "Bağnaz taraftar", "İnsanlar")],
    },
    "german": {
        "A1": [("COMPUTER", "Bilgisayar", "Teknoloji"), ("QUARK", "Lor peyniri", "Yiyecek ve İçecek"), ("UHR", "Saat", "Eşyalar"), ("VATER", "Baba", "İnsanlar"), ("XYLOFON", "Ksilofon", "Müzik"), ("YOGA", "Yoga", "Sağlık"), ("ÜBEN", "Pratik yapmak", "Fiiller")],
        "A2": [("CAMPING", "Kamp", "Seyahat"), ("IDEE", "Fikir", "Düşünce"), ("OBST", "Meyve", "Yiyecek ve İçecek"), ("PARTY", "Parti", "Günlük Yaşam"), ("QUITTUNG", "Makbuz", "Alışveriş"), ("URLAUB", "Tatil", "Seyahat"), ("XYLOFON", "Ksilofon", "Müzik"), ("YOGHURT", "Yoğurt", "Yiyecek ve İçecek"), ("ÄNDERN", "Değiştirmek", "Fiiller"), ("ÖFFENTLICH", "Halka açık", "Sıfatlar")],
        "B1": [("CHAOS", "Kaos", "Soyut Kavramlar"), ("DISKUSSION", "Tartışma", "İletişim"), ("INHALT", "İçerik", "İletişim"), ("JEDOCH", "Ancak", "Bağlaçlar"), ("KONFLIKT", "Çatışma", "Toplum"), ("ORGANISATION", "Organizasyon", "İş"), ("PFLICHT", "Görev", "İş"), ("XENOPHOBIE", "Yabancı düşmanlığı", "Toplum"), ("YACHT", "Yat", "Seyahat"), ("ÄHNLICH", "Benzer", "Sıfatlar"), ("ÖKONOMIE", "Ekonomi", "Toplum"), ("ÜBERZEUGUNG", "İnanç ve kanaat", "Düşünce")],
        "B2": [("CHANCENGLEICHHEIT", "Fırsat eşitliği", "Toplum"), ("DILEMMA", "İkilem", "Düşünce"), ("JURIST", "Hukukçu", "İnsanlar"), ("KONSENS", "Fikir birliği", "Toplum"), ("QUOTE", "Oran veya kota", "Toplum"), ("SACHLICH", "Nesnel", "Sıfatlar"), ("XENOPHOB", "Yabancı düşmanı", "Sıfatlar"), ("YUPPIE", "Kentli genç profesyonel", "İnsanlar"), ("ÄQUIVALENT", "Eşdeğer", "Sıfatlar"), ("ÖKOLOGISCH", "Ekolojik", "Doğa")],
        "C1": [("CHRONISCH", "Kronik", "Sıfatlar"), ("HINREICHEND", "Yeterli", "Sıfatlar"), ("JUXTAPOSITION", "Yan yana koyma", "Düşünce"), ("OBSOLET", "Kullanımdan kalkmış", "Sıfatlar"), ("XENOPHIL", "Yabancı kültürlere açık", "Sıfatlar"), ("YPSILON", "Y harfinin Almanca adı", "Dil"), ("ZWIESPÄLTIG", "İkircikli", "Sıfatlar"), ("ÄSTHETISCH", "Estetik", "Sıfatlar"), ("ÖKONOMISCH", "Ekonomik", "Sıfatlar"), ("ÜBERGEORDNET", "Üst düzey ve kapsayıcı", "Sıfatlar")],
        "C2": [("CHIMÄRE", "Kuruntu ve hayal", "Düşünce"), ("EPISTEMOLOGIE", "Bilgi felsefesi", "Bilim"), ("FAKTIZITÄT", "Olgusallık", "Düşünce"), ("JOVIAL", "Neşeli ve dostça", "Sıfatlar"), ("KONTINGENZ", "Olumsallık", "Düşünce"), ("METONYMIE", "Ad aktarması", "Dil"), ("NIHILISMUS", "Hiççilik", "Düşünce"), ("QUIESZENZ", "Durağanlık", "Soyut Kavramlar"), ("XENISMUS", "Yabancı dil ögesi", "Dil"), ("YLEM", "Evrenin varsayımsal ilk maddesi", "Bilim"), ("ÄQUIVOKATION", "Anlam bulanıklığı", "Dil"), ("ÖKUMENISCH", "Mezhepler arası", "Toplum"), ("ÜBERSCHWÄNGLICH", "Aşırı coşkulu", "Sıfatlar")],
    },
}

def normalize_answer(answer):
    return answer.upper()

def make_record(key, config, level, answer, clue, category):
    answer = normalize_answer(answer)
    record_id = uuid.uuid5(NAMESPACE, f"{key}:{level}:{answer}:{clue}")
    return {
        "id": str(record_id),
        "clue": clue,
        "extendedClue": f"{config['language']} dilinde karşılığını yaz.",
        "answer": answer,
        "difficulty": LEVEL_DIFFICULTY[level],
        "category": category,
        "letterCount": sum(char.isalpha() for char in answer),
        "initialLetter": next(char for char in answer if char.isalpha()),
        "letterRule": "startsWith",
        "sourceLanguage": "Turkish",
        "targetLanguage": config["language"],
        "locale": config["locale"],
        "cefrLevel": level
    }

def ensure_alphabet_coverage(key, config, level, records):
    counts = Counter(record["initialLetter"] for record in records)
    missing = [letter for letter in ALPHABETS[key] if counts[letter] == 0]
    candidates = {
        normalize_answer(entry[0])[0]: entry
        for entry in COVERAGE_PACKS[key][level]
    }
    for letter in missing:
        if letter not in candidates:
            raise ValueError(f"{key} {level}: {letter} harfi için kapsama sorusu yok")
        victim_index = next(
            (index for index in range(len(records) - 1, -1, -1)
             if counts[records[index]["initialLetter"]] > 1),
            None,
        )
        if victim_index is None:
            raise ValueError(f"{key} {level}: {letter} için değiştirilebilir soru yok")
        victim_letter = records[victim_index]["initialLetter"]
        counts[victim_letter] -= 1
        records[victim_index] = make_record(key, config, level, *candidates[letter])
        counts[letter] += 1
    uncovered = set(ALPHABETS[key]) - set(counts)
    if uncovered:
        raise ValueError(f"{key} {level}: eksik harfler {sorted(uncovered)}")
    return records

def main():
    output_dir = Path(__file__).resolve().parents[1] / "KelimeCemberi" / "Resources" / "Questions" / "Languages"
    output_dir.mkdir(parents=True, exist_ok=True)
    for key, config in PACKS.items():
        records = []
        for level, entries in config["levels"].items():
            level_records = [make_record(key, config, level, *entry) for entry in entries]
            level_records.extend(make_record(key, config, level, *entry) for entry in EXTRA_PACKS[key][level])
            records.extend(ensure_alphabet_coverage(key, config, level, level_records))
        path = output_dir / f"parola_cemberi_{key}_cefr.json"
        path.write_text(json.dumps(records, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
        print(f"{path.name}: {len(records)} kayıt")

if __name__ == "__main__":
    main()
